"""add report reference to agent messages

Revision ID: a48c435a7fab
Revises: 176954dba8d2
Create Date: 2026-07-11 16:35:24.591955

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a48c435a7fab'
down_revision: Union[str, Sequence[str], None] = '176954dba8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agent_messages_report_id'), 'agent_messages', ['report_id'], unique=False)
    op.create_foreign_key(None, 'agent_messages', 'reports', ['report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.drop_index(op.f('ix_agent_messages_report_id'), table_name='agent_messages')
    op.drop_column('agent_messages', 'report_id')
    # ### end Alembic commands ###
