"""add pipeline runs table

Revision ID: a8b231f20eeb
Revises: 5fe672b92091
Create Date: 2026-06-15 15:03:25.253251

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a8b231f20eeb'
down_revision: Union[str, Sequence[str], None] = '5fe672b92091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='pipelinerunstatus'), nullable=False),
    sa.Column('airflow_run_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_dataset_id'), 'pipeline_runs', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_dataset_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    sa.Enum(name='pipelinerunstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
